### ISSUE TITLE
browser entry field in the package.json file is incorrect.

### ISSUE THREAD

**Issue by blessanm86** [TanStack/react-location#216]
**Describe the bug**
All the packages have the [browser entry](https://github.com/TanStack/react-location/blob/main/packages/react-location/package.json#L28) field set to `build/umd/index.production.min.js` but the [rollup config](https://github.com/TanStack/react-location/blob/main/rollup.config.ts#L202) is outputting `build/umd/index.production.js` 

The above issue causes a problem when trying to import any package with parcel bundler.

**To Reproduce**

**Expected behavior**
Parcel should be able to resolve to correct file specified in the browser entry field.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: chrome
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by dotansimha** [comment]
I think this also causes issues with `vitest`: 

```
Error: Failed to resolve entry for package "react-location". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "react-location". The package may have incorrect main/module/exports specified in its package.json.
```
