### ISSUE TITLE
Failed to build with vitejs

### ISSUE THREAD

**Issue by oSethoum** [TanStack/react-location#222]
**Describe the bug**
Failed to build with vitejs

**Reproduce**

```jsx

import { Outlet, ReactLocation, Route, Router } from "react-location";
import { Home } from "./pages";

const location = new ReactLocation();

const routes: Route[] = [{
  path: "/",
  element: Home,
}];

export default function App() {
  return (
    <div>
      <Router location={location} routes={routes}>
        <Outlet />
      </Router>
    </div>
  );
}

```

**Screenshots**
![image](https://user-images.githubusercontent.com/88779394/154825831-b7424ffb-42dd-4155-bcda-6bb01cfaacd4.png)

**Desktop:**
 - OS: Windows 10 64bits

**Comment by hugobdev** [comment]
This was fixed in #223 (not yet released)

**Comment by blessanm86** [comment]
@hugobdev I see [this pre release](https://github.com/TanStack/react-location/releases/tag/v3.6.2). Do you know how to install this with npm? Like what the command is.

**Comment by bkoether** [comment]
@hugobdev Having the same issue. Both npm and yarn registries are stuck on version 3.6.1

**Comment by hugobdev** [comment]
I'm not responsible for releasing, just contributed some code
